### ISSUE TITLE
Jcrop inside form, submits form on moving selected area

### ISSUE THREAD

**Issue by phillipsnick** [tapmodo/Jcrop#197]
I have to place my image with Jcrop applied inside `<form>` tags due to the design of the page. Unfortunately when you move the selected area the form is submitted on release.

Test code which:
  
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Test</title>
    <link rel="stylesheet" href="Jcrop/css/Jcrop.css">
</head>
<body>
    <form method="post" action="form.html">
        <img src="example.png" id="tool" alt="Image editor">
    </form>

    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="Jcrop/js/Jcrop.js"></script>
    <script>
        $().ready(function() {
            $('#tool').Jcrop({});
        });
    </script>
</body>
</html>
```

**Comment by spooky** [comment]
+1

**Comment by tapmodo** [comment]
Is this the behavior of a particular browser, or universal?
It definitely shouldn't be doing that...

**Comment by spooky** [comment]
For me it manifested on Chrome and Firefox. Hadn't tried IE or Safari.

**Comment by lboaretto** [comment]
+1

**Comment by tapmodo** [comment]
In v2 some of the cropping interface is actually `<button>` elements. It may be submitting the form based on some default event being triggered on the first button (similar to how it might submit if you press enter in a text field—as far as I know, that is essentially submitting using the first button).

I'm going to look into it. I'm also going to switch the tags from review to confirmed based on @lboaretto test results. In the meantime, if anyone has a fix they've developed, chime in.

**Comment by ruskid** [comment]
```js
$image.Jcrop({
            onChange: showPreview,
            onSelect: showPreview,
            aspectRatio: 1,
            bgColor: 'black',
            bgOpacity: .4,
            minSize: [100, 100],
            setSelect: [x, y, x2, y2],
            boxWidth: 435,
            boxHeight: 600
        }, function () {//fix. prevent submit form
            $(".jcrop-box").attr('type', 'button');
        });

```

**Comment by healqq** [comment]
Fixed this issue the same way @ruskid  did.
Don't forget, that if you destroy or use mutiple selections, you need to add type every time new selection is created.

**Comment by tapmodo** [comment]
Can someone verify that the newest commit (v2.0.3) fixes this issue?  
Thanks @healqq for the patch!

**Comment by joelklingler** [comment]
@tapmodo I tried including Jcrop (the latest version) with cdn as shown on jcrop.org. The problem still occurs even with the fix from @ruskid. Maybe I'm doing the fix wrong but anyways, the issue still exists on the latest cdn version.

**Comment by healqq** [comment]
@joelklingler hello! Can you please show, what link to CDN do you use? Seems like it still serves 2.0.0 version instead of 2.0.3. Can you use bower instead?

**Comment by joelklingler** [comment]
Hello @healqq - I use(d) the following CDN links from this documentation: http://jcrop.org/doc/quickstart

There is no newer CDN linked.

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://jcrop-cdn.tapmodo.com/v2.0.0-RC1/js/Jcrop.js"></script>
<link rel="stylesheet" href="http://jcrop-cdn.tapmodo.com/v2.0.0-RC1/css/Jcrop.css" type="text/css">

**Comment by healqq** [comment]
I'm not sure if CDN link exists.  Here are links to required files: https://github.com/tapmodo/Jcrop/blob/WIP-2.x/js/Jcrop.js, https://github.com/tapmodo/Jcrop/blob/WIP-2.x/css/Jcrop.css. If you need minified versions, you can get them in folders js and css on github repo.

**Comment by joelklingler** [comment]
@healqq Thank you!

**Comment by healqq** [comment]
@joelklingler did it fix your problem?

**Comment by joelklingler** [comment]
I found an older Jcrop-version (v0.9.12) from an other project. It works fine there. I didn't try out the v2.0.3 version.

**Comment by mosinski** [comment]
@ruskid ruskid :+1:

**Comment by jrmadsen67** [comment]
Is a new CDN going to be posted? It's been a year now

**Comment by ojsoft** [comment]
The problem still exists in the current version, but the fix from ruskid works very well in my project. It's only a RC version, so I guess there are working on the last issues.

**Comment by joelklingler** [comment]
@ojsoft The last commit on the WIP version was made on Nov 18, 2015.
